package com.example.libreriap2

object BookProvider {
    private val books: Map<Int, Book> = mapOf(
            1 to Book(
                "1",
                "El Principito",
                "Antoine de Saint-Exupéry",
                "https://upload.wikimedia.org/wikipedia/commons/1/1c/El_principito.jpg",
                "1943",
                "El Principito es una novela corta y la obra más famosa del escritor y aviador francés Antoine de Saint-Exupéry. Publicado por primera vez en 1943, es un libro que ha sido traducido a cientos de idiomas y se ha convertido en un clásico de la literatura universal",
                "La Palma",
                22,
                68,
                "Español",
                6,
                85.00
            ),
            /*2 to Book(
                "2",
                "1984",
                "George Orwell",
                "https://imagessl4.casadellibro.com/a/l/s5/44/9788499890944.webp",
                "1949",
                "1984 es una novela política de ficción distópica, escrita por George Orwell entre 1947 y 1948 y publicada el 8 de junio de 1949.",
                "Penguin Random House",
                15,
                328,
                "Inglés",
                16,
                120.00
            ),
            3 to Book(
                "3",
                "Cien años de soledad",
                "Gabriel García Márquez",
                "https://m.media-amazon.com/images/I/91TvVQS7loL._AC_UF1000,1000_QL80_.jpg",
                "1967",
                "Cien años de soledad es una novela del escritor colombiano Gabriel García Márquez, ganador del Premio Nobel de Literatura en 1982.",
                "Vintage Español",
                10,
                432,
                "Español",
                18,
                150.00
            ),
            4 to Book(
                "4",
                "El Gran Gatsby",
                "F. Scott Fitzgerald",
                "https://www.elsotano.com/imagenes_grandes/9788418/978841839518.JPG",
                "1925",
                "El Gran Gatsby es una novela escrita por F. Scott Fitzgerald y publicada por primera vez en 1925. La historia sigue al millonario Jay Gatsby y su búsqueda del amor en la década de 1920.",
                "Scribner",
                20,
                180,
                "Inglés",
                18,
                95.00
            ),
            5 to Book(
                "5",
                "Matar a un ruiseñor",
                "Harper Lee",
                "https://m.media-amazon.com/images/I/81+j6JIEweL._AC_UF1000,1000_QL80_.jpg",
                "1960",
                "Matar a un ruiseñor es una novela escrita por Harper Lee y publicada en 1960. Ambientada en la década de 1930 en el sur de Estados Unidos, la historia sigue a la joven Scout Finch mientras su padre, Atticus, defiende a un hombre negro acusado de violación.",
                "J. B. Lippincott & Co.",
                18,
                281,
                "Inglés",
                14,
                110.00
            ),
            6 to Book(
                "6",
                "Orgullo y prejuicio",
                "Jane Austen",
                "https://www.planetadelibros.com.mx/usuaris/libros/fotos/383/m_libros/portada_orgullo-y-prejuicio_jane-austen_202308011307.jpg",
                "1813",
                "Orgullo y prejuicio es una novela de la escritora británica Jane Austen, publicada por primera vez en 1813. La historia sigue a Elizabeth Bennet mientras navega por las complejidades del amor y la sociedad en la Inglaterra del siglo XIX.",
                "T. Egerton, Whitehall",
                25,
                279,
                "Inglés",
                16,
                80.00
            ),
            7 to Book(
                "7",
                "La sombra del viento",
                "Carlos Ruiz Zafón",
                "https://m.media-amazon.com/images/I/919J8I9S6QL._AC_UF1000,1000_QL80_.jpg",
                "2001",
                "La sombra del viento es una novela escrita por el autor español Carlos Ruiz Zafón y publicada en 2001. Ambientada en la Barcelona de la posguerra, la historia sigue al joven Daniel Sempere mientras descubre un misterioso libro en el Cementerio de los Libros Olvidados.",
                "Planeta",
                30,
                560,
                "Español",
                16,
                150.00
            ),
            8 to Book(
                "8",
                "Don Quijote de la Mancha",
                "Miguel de Cervantes",
                "https://m.media-amazon.com/images/I/71kdJikvR4L._AC_UF1000,1000_QL80_.jpg",
                "1605",
                "Don Quijote de la Mancha es una novela escrita por el autor español Miguel de Cervantes y publicada en dos partes, en 1605 y 1615. Considerada una de las mejores obras de la literatura universal, la historia sigue las aventuras del caballero Don Quijote y su fiel escudero Sancho Panza.",
                "Juan de la Cuesta",
                40,
                863,
                "Español",
                18,
                200.00
            ),
            9 to Book(
                "9",
                "Rayuela",
                "Julio Cortázar",
                "https://upload.wikimedia.org/wikipedia/commons/c/ca/Rayuela_JC.png",
                "1963",
                "Rayuela es una novela escrita por el autor argentino Julio Cortázar y publicada en 1963. Conocida por su estructura no lineal y su estilo experimental, la historia sigue al protagonista Horacio Oliveira mientras navega por sus experiencias en París y Buenos Aires.",
                "Editorial Sudamericana",
                20,
                600,
                "Español",
                20,
                170.00
            ),
            10 to Book(
                "10",
                "La casa de los espíritus",
                "Isabel Allende",
                "https://m.media-amazon.com/images/I/914oLv5QzaL._AC_UF1000,1000_QL80_.jpg",
                "1982",
                "La casa de los espíritus es una novela escrita por la autora chilena Isabel Allende y publicada en 1982. La historia sigue a la familia Trueba a lo largo de varias generaciones en un país sudamericano no especificado, explorando temas como el amor, la política y la magia.",
                "Plaza & Janés",
                15,
                450,
                "Español",
                18,
                140.00
            ),
            11 to Book(
                "11",
                "Los renglones torcidos de Dios",
                "Torcuato Luca de Tena",
                "https://m.media-amazon.com/images/I/71o+3AdQCsL._AC_UF1000,1000_QL80_.jpg",
                "1979",
                "Los renglones torcidos de Dios es una novela escrita por el autor español Torcuato Luca de Tena y publicada en 1979. La historia sigue a la psiquiatra Ana María Salomón mientras investiga el misterioso caso de una paciente ingresada en un hospital psiquiátrico.",
                "Editorial Planeta",
                12,
                320,
                "Español",
                18,
                120.00
            ),
            12 to Book(
                "12",
                "La ciudad y los perros",
                "Mario Vargas Llosa",
                "https://m.media-amazon.com/images/I/71EyHH99GfL._AC_UF1000,1000_QL80_.jpg",
                "1963",
                "La ciudad y los perros es una novela escrita por el autor peruano Mario Vargas Llosa y publicada en 1963. Ambientada en un colegio militar en Lima, Perú, la historia sigue a un grupo de jóvenes cadetes mientras luchan por sobrevivir en un entorno marcado por la violencia y la corrupción.",
                "Seix Barral",
                18,
                400,
                "Español",
                16,
                110.00
            ),
            13 to Book(
                "13",
                "La Regenta",
                "Leopoldo Alas Clarín",
                "https://m.media-amazon.com/images/I/61LFMR6xGsL._AC_UF894,1000_QL80_.jpg",
                "1884",
                "La Regenta es una novela escrita por el autor español Leopoldo Alas Clarín y publicada en 1884. Ambientada en una ciudad de provincias en el norte de España, la historia sigue la vida de Ana Ozores, una mujer atrapada en un matrimonio infeliz y en un ambiente social opresivo.",
                "Espasa-Calpe",
                22,
                700,
                "Español",
                18,
                130.00
            ),
            14 to Book(
                "14",
                "La Sombra",
                "John Katzenbach",
                "https://m.media-amazon.com/images/I/914lkuwDnCL._AC_UF894,1000_QL80_.jpg",
                "2002",
                "La Sombra es una novela escrita por el autor estadounidense John Katzenbach y publicada en 2002. La historia sigue a un hombre que, tras perder a su esposa e hija en un accidente, se ve envuelto en una trama de venganza y misterio.",
                "Ediciones B",
                20,
                480,
                "Español",
                18,
                140.00
            ),
            15 to Book(
                "15",
                "La Catedral del Mar",
                "Ildefonso Falcones",
                "https://m.media-amazon.com/images/I/912JG9bB8XL._AC_UF1000,1000_QL80_DpWeblab_.jpg",
                "2006",
                "La Catedral del Mar es una novela escrita por el autor español Ildefonso Falcones y publicada en 2006. Ambientada en la Barcelona del siglo XIV, la historia sigue la vida de Arnau Estanyol, un siervo que lucha por construir una catedral para la Virgen María.",
                "Grijalbo",
                25,
                800,
                "Español",
                16,
                160.00
            ),
            16 to Book(
                "16",
                "El Perfume: Historia de un asesino",
                "Patrick Süskind",
                "https://m.media-amazon.com/images/I/91LSFx5oCbL._AC_UF894,1000_QL80_.jpg",
                "1985",
                "El Perfume: Historia de un asesino es una novela escrita por el autor alemán Patrick Süskind y publicada en 1985. La historia sigue a Jean-Baptiste Grenouille, un perfumista con un sentido del olfato extraordinario, mientras busca crear el perfume perfecto utilizando esencias humanas.",
                "Seix Barral",
                20,
                272,
                "Español",
                18,
                130.00
            ),
            17 to Book(
                "17",
                "El paciente",
                "Juan Gómez-Jurado",
                "https://m.media-amazon.com/images/I/71MHX8cMHnL._AC_UF1000,1000_QL80_.jpg",
                "2014",
                "El paciente es una novela escrita por el autor español Juan Gómez-Jurado y publicada en 2014. La historia sigue a un psiquiatra que se ve envuelto en una conspiración internacional mientras investiga el caso de un paciente con amnesia.",
                "Ediciones B",
                25,
                464,
                "Español",
                16,
                140.00
            ),
            18 to Book(
                "18",
                "La verdad sobre el caso Harry Quebert",
                "Joël Dicker",
                "https://www.elsotano.com/imagenes_grandes/9786071/978607112646.JPG",
                "2012",
                "La verdad sobre el caso Harry Quebert es una novela escrita por el autor suizo Joël Dicker y publicada en 2012. La historia sigue al escritor Marcus Goldman mientras investiga el caso de su mentor, Harry Quebert, acusado de asesinar a una joven de 15 años.",
                "Alfaguara",
                30,
                640,
                "Español",
                18,
                150.00
            ),
            19 to Book(
                "19",
                "El fin del mundo y un despiadado país de las maravillas",
                "Haruki Murakami",
                "https://www.planetadelibros.com.mx/usuaris/libros/fotos/231/m_libros/portada_el-fin-del-mundo-y-un-despiadado-pais-de-las-marav_haruki-murakami_201609131929.jpg",
                "2010",
                "El fin del mundo y un despiadado país de las maravillas es una novela escrita por el autor japonés Haruki Murakami y publicada en 2010. La historia sigue a un hombre llamado Tengo mientras se ve envuelto en una trama misteriosa que involucra a un culto religioso y una novela enigmática.",
                "Tusquets Editores",
                22,
                624,
                "Español",
                18,
                140.00
            ),
            20 to Book(
                "20",
                "El libro de los Baltimore",
                "Joël Dicker",
                "https://m.media-amazon.com/images/I/71Emo1cLdTL._AC_UF1000,1000_QL80_.jpg",
                "2015",
                "El libro de los Baltimore es una novela escrita por el autor suizo Joël Dicker y publicada en 2015. La historia sigue a Marcus Goldman mientras investiga el pasado oscuro de su familia y los secretos que rodean a los Baltimore, una familia adinerada con la que su familia está estrechamente relacionada.",
                "Alfaguara",
                28,
                560,
                "Español",
                18,
                140.00
            ),
            21 to Book(
                "21",
                "La chica del tren",
                "Paula Hawkins",
                "https://m.media-amazon.com/images/I/41KEMBmpWaL.jpg",
                "2015",
                "La chica del tren es una novela escrita por la autora británica Paula Hawkins y publicada en 2015. La historia sigue a Rachel Watson, una mujer que se obsesiona con una pareja aparentemente perfecta que ve desde el tren, y se ve envuelta en un misterio cuando la mujer desaparece.",
                "Planeta",
                35,
                392,
                "Español",
                16,
                150.00
            ),
            22 to Book(
                "22",
                "El Informe Pelícano",
                "John Grisham",
                "https://www.elsotano.com/imagenes_grandes/9789708/978970810250.JPG",
                "1992",
                "El Informe Pelícano es una novela escrita por el autor estadounidense John Grisham y publicada en 1992. La historia sigue a un estudiante de derecho y a una reportera mientras investigan un escándalo de corrupción gubernamental y luchan por exponer la verdad.",
                "Random House Mondadori",
                20,
                432,
                "Español",
                18,
                120.00
            ),
            23 to Book(
                "23",
                "El nombre del viento",
                "Patrick Rothfuss",
                "https://m.media-amazon.com/images/I/71Koo4MN6wS._AC_UF1000,1000_QL80_.jpg",
                "2007",
                "El nombre del viento es una novela escrita por el autor estadounidense Patrick Rothfuss y publicada en 2007. La historia sigue a Kvothe, un músico y aventurero, mientras relata las experiencias que lo llevaron a convertirse en una leyenda viva.",
                "Plaza & Janés",
                25,
                880,
                "Español",
                18,
                160.00
            ),
            24 to Book(
                "24",
                "La ladrona de libros",
                "Markus Zusak",
                "https://images.cdn3.buscalibre.com/fit-in/360x360/a5/b3/a5b3ad34ab8ac802b64605029de9c1f7.jpg",
                "2005",
                "La ladrona de libros es una novela escrita por el autor australiano Markus Zusak y publicada en 2005. Ambientada en la Alemania nazi, la historia sigue a Liesel Meminger, una niña adoptada que roba libros y comparte su amor por la lectura en un momento de oscuridad y guerra.",
                "Lumen",
                18,
                560,
                "Español",
                14,
                130.00
            ),
            25 to Book(
                "25",
                "Norwegian Wood",
                "Haruki Murakami",
                "https://m.media-amazon.com/images/I/81zqVhvbHbL._AC_UF894,1000_QL80_.jpg",
                "1987",
                "Norwegian Wood es una novela escrita por el autor japonés Haruki Murakami y publicada en 1987. La historia sigue a Toru Watanabe mientras reflexiona sobre su juventud y su relación con dos mujeres, Naoko y Midori, durante un período de agitación social en la década de 1960 en Japón.",
                "Tusquets Editores",
                22,
                400,
                "Español",
                18,
                140.00
            ),
            26 to Book(
                "26",
                "1Q84",
                "Haruki Murakami",
                "https://www.planetadelibros.com.mx/usuaris/libros/fotos/71/m_libros/1q84-libros-1-y-2_9788483836262.jpg",
                "2009",
                "1Q84 es una novela escrita por el autor japonés Haruki Murakami y publicada en 2009. La historia sigue a dos personajes, Aomame y Tengo, mientras se ven envueltos en un mundo alternativo donde existen extrañas criaturas y realidades distorsionadas.",
                "Tusquets Editores",
                30,
                1232,
                "Español",
                18,
                200.00
            ),
            27 to Book(
                "27",
                "Kafka en la orilla",
                "Haruki Murakami",
                "https://m.media-amazon.com/images/I/81AwOfVpR2L._AC_UF1000,1000_QL80_.jpg",
                "2002",
                "Kafka en la orilla es una novela escrita por el autor japonés Haruki Murakami y publicada en 2002. La historia sigue a dos personajes, Kafka Tamura, un adolescente que huye de casa, y Nakata, un hombre mayor con habilidades especiales, mientras sus vidas se entrelazan en un viaje surrealista.",
                "Tusquets Editores",
                25,
                600,
                "Español",
                18,
                160.00
            ),
            28 to Book(
                "28",
                "Tokio blues",
                "Haruki Murakami",
                "https://m.media-amazon.com/images/I/71YpNgq+1dL._AC_UF1000,1000_QL80_.jpg",
                "1987",
                "Tokio blues es una novela escrita por el autor japonés Haruki Murakami y publicada en 1987. La historia sigue a Toru Watanabe mientras reflexiona sobre su juventud y su relación con dos mujeres, Naoko y Midori, durante un período de agitación social en la década de 1960 en Japón.",
                "Tusquets Editores",
                22,
                400,
                "Español",
                18,
                140.00
            ),
            29 to Book(
                "29",
                "After Dark",
                "Haruki Murakami",
                "https://m.media-amazon.com/images/I/91mlPVcYHtL._AC_UF1000,1000_QL80_.jpg",
                "2004",
                "After Dark es una novela escrita por el autor japonés Haruki Murakami y publicada en 2004. La historia sigue a varios personajes en Tokio durante una noche, explorando temas como la soledad, la conexión humana y la oscuridad que acecha en la ciudad durante la noche.",
                "Tusquets Editores",
                28,
                256,
                "Español",
                16,
                130.00
            ),
            30 to Book(
                "30",
                "Memorias de una geisha",
                "Arthur Golden",
                "https://www.elsotano.com/imagenes_grandes/9786073/978607315606.JPG",
                "1997",
                "Memorias de una geisha es una novela escrita por el autor estadounidense Arthur Golden y publicada en 1997. La historia sigue la vida de una joven llamada Chiyo, quien es vendida a una casa de geishas en Kyoto y se convierte en una famosa geisha llamada Sayuri.",
                "Vintage Español",
                20,
                512,
                "Español",
                16,
                150.00
            ),
            31 to Book(
                31,
                "Battle Royale",
                "Koushun Takami",
                "https://m.media-amazon.com/images/I/81NGvQ0QxdL._AC_UF1000,1000_QL80_.jpg",
                "1999",
                "Battle Royale es una novela escrita por el autor japonés Koushun Takami y publicada en 1999. La historia sigue a un grupo de estudiantes obligados a participar en un juego mortal en el que solo uno puede sobrevivir.",
                "Holt Paperbacks",
                25,
                688,
                "Español",
                18,
                160.00
            ),
            32 to Book(
                32,
                "La chica que saltaba a través del tiempo",
                "Yasutaka Tsutsui",
                "https://4.bp.blogspot.com/-drjfW2PgU3c/T20CgrQ9XNI/AAAAAAAABQ8/eWP0rDuCZ4Q/w1200-h630-p-k-no-nu/5641383253_16b123bb32.jpg",
                "1967",
                "La chica que saltaba a través del tiempo es una novela escrita por el autor japonés Yasutaka Tsutsui y publicada en 1967. La historia sigue a una joven llamada Kazuko mientras descubre que tiene la habilidad de viajar en el tiempo y las consecuencias de sus acciones.",
                "Harcourt",
                18,
                224,
                "Español",
                14,
                120.00
            ),
            33 to Book(
                33,
                "Nieve de primavera",
                "Yukio Mishima",
                "https://m.media-amazon.com/images/I/51S0aS+FY6L._AC_UF1000,1000_QL80_.jpg",
                "1969",
                "Nieve de primavera es una novela escrita por el autor japonés Yukio Mishima y publicada en 1969. La historia sigue a un joven llamado Honda mientras reflexiona sobre su vida y sus encuentros con un famoso poeta.",
                "Vintage Español",
                22,
                180,
                "Español",
                16,
                130.00
            ),
            34 to Book(
                34,
                "Kokoro",
                "Natsume Soseki",
                "https://m.media-amazon.com/images/I/316l4hyMwhL._AC_UF1000,1000_QL80_.jpg",
                "1914",
                "Kokoro es una novela escrita por el autor japonés Natsume Soseki y publicada en 1914. La historia explora las complejas relaciones humanas y las tensiones entre generaciones en el Japón de principios del siglo XX.",
                "Vintage Español",
                20,
                272,
                "Español",
                16,
                140.00
            ),
            35 to Book(
                35,
                "La casa de las bellas durmientes",
                "Yasunari Kawabata",
                "https://m.media-amazon.com/images/I/81VENDlQOzL._AC_UF1000,1000_QL80_.jpg",
                "1961",
                "La casa de las bellas durmientes es una novela escrita por el autor japonés Yasunari Kawabata y publicada en 1961. La historia sigue a un hombre mayor que visita una casa donde puede pasar la noche con mujeres dormidas, explorando temas de la mortalidad y el deseo.",
                "Alfaguara",
                20,
                192,
                "Español",
                18,
                140.00
            ),
            36 to Book(
                36,
                "Después del terremoto",
                "Haruki Murakami",
                "https://m.media-amazon.com/images/I/81sbswp5DpL._AC_UF1000,1000_QL80_.jpg",
                "2000",
                "Después del terremoto es una colección de relatos cortos escrita por el autor japonés Haruki Murakami y publicada en 2000. Los cuentos exploran las secuelas emocionales y psicológicas del terremoto de Kobe de 1995 en la vida de los personajes.",
                "Tusquets Editores",
                22,
                256,
                "Español",
                18,
                150.00
            ),
            37 to Book(
                37,
                "Los años de peregrinación del chico sin color",
                "Haruki Murakami",
                "https://m.media-amazon.com/images/I/817OGI5z3DL._AC_UF894,1000_QL80_.jpg",
                "2013",
                "Los años de peregrinación del chico sin color es una novela escrita por el autor japonés Haruki Murakami y publicada en 2013. La historia sigue a un hombre joven sin nombre mientras reflexiona sobre su vida y sus relaciones pasadas mientras viaja por Japón y Europa.",
                "Tusquets Editores",
                25,
                400,
                "Español",
                18,
                160.00
            ),
            38 to Book(
                38,
                "Crimen y castigo",
                "Fiódor Dostoyevski",
                "https://i1.whakoom.com/large/10/3b/be8ab05a9a0946d5a0012b468a8ba551.jpg",
                "1866",
                "Crimen y castigo es una novela escrita por el autor ruso Fiódor Dostoyevski y publicada en 1866. La historia sigue a Rodion Raskólnikov, un estudiante que comete un crimen por razones filosóficas, y explora temas como la moralidad, la redención y el castigo.",
                "Penguin Clásicos",
                20,
                592,
                "Español",
                18,
                120.00
            ),
            39 to Book(
                39,
                "Guerra y paz",
                "León Tolstói",
                "https://images.cdn3.buscalibre.com/fit-in/360x360/27/e6/27e64a187a4ef69f848cbff542049074.jpg",
                "1869",
                "Guerra y paz es una novela épica escrita por el autor ruso León Tolstói y publicada en 1869. La historia sigue a varios personajes aristocráticos rusos durante las Guerras Napoleónicas y explora temas como el amor, la guerra y la filosofía.",
                "Alba Editorial",
                30,
                1500,
                "Español",
                18,
                200.00
            ),
            40 to Book(
                40,
                "El maestro y Margarita",
                "Mijaíl Bulgákov",
                "https://m.media-amazon.com/images/I/81lwJ8bdEJS._AC_UF1000,1000_QL80_.jpg",
                "1967",
                "El maestro y Margarita es una novela escrita por el autor ruso Mijaíl Bulgákov y publicada póstumamente en 1967. La historia combina elementos de sátira política, comedia negra y fantasía, y sigue las aventuras de Satanás y sus secuaces en la Moscú de Stalin.",
                "Alfaguara",
                25,
                416,
                "Español",
                18,
                140.00
            ),
            41 to Book(
                41,
                "Anna Karénina",
                "León Tolstói",
                "https://m.media-amazon.com/images/I/71wLs1YK8yL._AC_UF1000,1000_QL80_.jpg",
                "1877",
                "Anna Karénina es una novela escrita por el autor ruso León Tolstói y publicada en 1877. La historia sigue a Anna Karénina, una mujer atrapada en un matrimonio infeliz, y explora temas como el amor prohibido, la familia y la sociedad.",
                "Penguin Clásicos",
                22,
                864,
                "Español",
                18,
                160.00
            ),
            42 to Book(
                42,
                "El idiota",
                "Fiódor Dostoyevski",
                "https://m.media-amazon.com/images/I/91LTTPpVARL._AC_UF1000,1000_QL80_.jpg",
                "1869",
                "El idiota es una novela escrita por el autor ruso Fiódor Dostoyevski y publicada en 1869. La historia sigue a un hombre llamado el príncipe Mischkin mientras navega por la sociedad rusa y lucha por mantener su pureza espiritual en un mundo corrupto.",
                "Penguin Clásicos",
                18,
                656,
                "Español",
                18,
                130.00
            ),
            43 to Book(
                43,
                "Los hermanos Karamázov",
                "Fiódor Dostoyevski",
                "https://images.cdn3.buscalibre.com/fit-in/360x360/7b/b1/7bb12823686e96de54d1827f51c07114.jpg",
                "1880",
                "Los hermanos Karamázov es una novela escrita por el autor ruso Fiódor Dostoyevski y publicada en 1880. La historia sigue a los hermanos Dmitri, Iván y Aliosha Karamázov mientras enfrentan conflictos familiares, dilemas morales y cuestiones filosóficas.",
                "Penguin Clásicos",
                24,
                976,
                "Español",
                18,
                180.00
            ),
            44 to Book(
                44,
                "La muerte de Iván Ilich",
                "León Tolstói",
                "https://m.media-amazon.com/images/I/51oc0CrWVQL.jpg",
                "1886",
                "La muerte de Iván Ilich es una novela corta escrita por el autor ruso León Tolstói y publicada en 1886. La historia sigue a Iván Ilich, un funcionario de la burocracia rusa, mientras enfrenta su propia mortalidad y reflexiona sobre el significado de la vida.",
                "Penguin Clásicos",
                18,
                160,
                "Español",
                16,
                100.00
            ),
            45 to Book(
                45,
                "La dama del perrito y otros cuentos",
                "Antón Chéjov",
                "https://imagessl3.casadellibro.com/a/l/s5/03/9789500398503.webp",
                "1899",
                "La dama del perrito y otros cuentos es una colección de relatos escrita por el autor ruso Antón Chéjov y publicada en 1899. Los cuentos exploran temas como el amor, la soledad y la condición humana a través de vívidos retratos de la vida rusa.",
                "Alba Editorial",
                20,
                320,
                "Español",
                16,
                120.00
            ),
            46 to Book(
                46,
                "El jugador",
                "Fiódor Dostoyevski",
                "https://assets-global.website-files.com/6034d7d1f3e0f52c50b2adee/6254290ee18d54a50d008b33_618b8faa8965fbda9ae3f943_el20jugador.jpeg",
                "1867",
                "El jugador es una novela escrita por el autor ruso Fiódor Dostoyevski y publicada en 1867. La historia sigue a un joven tutor llamado Alexéi Ivánovich mientras se ve envuelto en los juegos de azar y las intrigas amorosas en un balneario alemán.",
                "Penguin Clásicos",
                16,
                256,
                "Español",
                18,
                110.00
            ),*/
            47 to Book(
                "47",
                "El zar saltan",
                "Nikolái Gógol",
                "https://www.editorialrenacimiento.com/5500-large_default/el-zar-saltan.jpg",
                "1836",
                "El zar saltan es una novela escrita por el autor ruso Nikolái Gógol y publicada en 1836. La historia sigue las absurdas aventuras del joven zar saltan mientras viaja por su reino, y satiriza la corrupción y la incompetencia del gobierno ruso.",
                "Penguin Clásicos",
                14,
                192,
                "Español",
                14,
                90.00
            )
            // Agregar más libros según sea necesario
        )

    fun getSampleBooks(): List<Book> {
        return books.values.toList()
    }

    fun getBookById(id: Int): Book? {
        return books[id]
    }
}
